### ISSUE TITLE
How should I operate non-root cell

### ISSUE THREAD

**Issue by Fafrotskies** [xCocco0/jailhouse-on-rpi4#1]
I used `sudo ./run.sh enable` and `sudo ./run.sh start` to start non-root cell. It just shows `Started cell "rpi4-linux-demo"` in 'jailhouse console'. Is this normal? 
So what should I do to connect the non-root cell linux and operate it . Thanks

**Comment by xCocco0** [comment]
I think the easiest way is to use a serial adapter, you will see both jailhouse debug and the kernel boot debug

**Comment by xCocco0** [comment]
I think the easiest way is to use a serial adapter, you will see both the jailhouse output and kernel boot messages on the serial output.
As an alternative, you may want to enable SSH to connect to the cell. The script automatically setup a DHCP server for dynamically allocating IPs to the cell, but remember that:
- You need to have an SSH server running on the non-root cell (if you used my config it should already be bundled in the rootfs)
- You need to properly setup the name of the virtual interface created in the config (see ``build.config``)

Alternatively, if you want to use static addressing, you can pass an address directely on the kernel cmdline of the cell (unfortunately, I didn't have much luck here).

**Comment by Fafrotskies** [comment]
Thank you for your suggestion
